import type {Metadata} from "next";
import {Vazirmatn} from "next/font/google";
import "./globals.css";
import {StoreProvider} from "@/app/StoreProvider";

const vazir = Vazirmatn({subsets: ["arabic", "latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <StoreProvider>
        <html lang="en">
        <body className={"flex justify-center items-center min-h-screen p-24 " + vazir.className}>
        {children}
        </body>
        </html>
      </StoreProvider>
  );
}
